name: create_db

on:
  push:
    paths:
      - setup/R/db/create_de_tables.R
      - setup/R/db/functions.R

jobs: 
  build:
  
    runs-on: ubuntu-latest 

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 2000:27017

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: install libcurl
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev libsasl2-dev

      - name: Install remotes
        run: |
            install.packages('remotes')
        shell: Rscript {0}

      - name: Cache R packages
        id: cache-packages
        uses: actions/cache@v2
        with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-create_de_tables2

      - name: Query dependencies
        run: |
            remotes::install_cran('AUC')
            remotes::install_cran('dplyr')
            remotes::install_cran('argparse')
            remotes::install_cran('mongolite')

        shell: Rscript {0}

      - name: Test create_de_tables script
        run: cd setup/R/db && Rscript create_de_tables.R

