name: process_data 

on: 
    push:
        paths:
            - setup/R/process/process_*.R
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true

    - name: Set up R 
      uses: r-lib/actions/setup-r@v1

    - name: install libcurl
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Install remotes 
      run: |
          install.packages('remotes')
      shell: Rscript {0}

    - name: Cache R packages
      id: cache-packages
      uses: actions/cache@v2
      with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-GEOquery-3

    - name: Query dependencies
      run: |
          remotes::install_bioc('GEOquery')
          remotes::install_bioc('impute')
          remotes::install_cran('dplyr')
          remotes::install_cran('UCSCXenaTools')
          remotes::install_cran('edgeR')
          remotes::install_cran('ggplot2')
      shell: Rscript {0}

    - id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true

    - name: Test new/modified processing scripts 
      run:  |
            cd setup/R/process
            for changed_file in ${{ steps.files.outputs.added_modified }}; do
                if [[ "$changed_file" == "setup/R/process/process_"* ]]; then
                    echo "Rscript ${changed_file##*/}."
                    Rscript ${changed_file##*/}
                fi
            done

    - name: Validate IDs 
      run:  cd setup/R/process/ && Rscript validate.R
